name: Publish Nightly Build

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UT
  workflow_dispatch:

concurrency:
  group: ci-repo-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

# https://typicode.github.io/husky/how-to.html#ci-server-and-docker
env:
  HUSKY: 0

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux
          - os: macos-latest
            arch: macos
          - os: windows-latest
            arch: windows
      max-parallel: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install workspace dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

  package:
    name: Package (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install workspace dependencies
        run: |
          npm ci

      - name: Build the project and generate the .vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm run collect-assets -- --use-workflow-artifacts --branch=main
          npm run dist
          npm run package

      - name: zip vsix
        run: |
          cd ./dist
          zip vscode-extension-nightly.zip *.vsix
          cd ..

      - name: Deploy release
        uses: WebFreak001/deploy-nightly@v3.2.0
        with:
          upload_url: https://uploads.github.com/repos/jmontleon/editor-extensions/releases/223191864/assets{?name,label}
          release_id: 223191864
          asset_path: ./dist/vscode-extension-nightly.zip
          asset_name: vscode-extension-nightly-$$.zip
          asset_content_type: application/zip
          max_releases: 14
          ignore_hash: true
